import { Exercise, Workout, Achievement, MuscleGroup } from '../types';

export const MUSCLE_GROUP_LABELS: Record<MuscleGroup, string> = {
  chest: 'Chest',
  back: 'Back',
  shoulders: 'Shoulders',
  biceps: 'Biceps',
  triceps: 'Triceps',
  legs: 'Legs',
  core: 'Core',
  glutes: 'Glutes',
  calves: 'Calves',
  forearms: 'Forearms',
  full_body: 'Full Body',
  cardio: 'Cardio',
};

export const MUSCLE_GROUP_ICONS: Record<MuscleGroup, string> = {
  chest: 'fitness-center',
  back: 'fitness-center',
  shoulders: 'fitness-center',
  biceps: 'fitness-center',
  triceps: 'fitness-center',
  legs: 'directions-run',
  core: 'fitness-center',
  glutes: 'directions-run',
  calves: 'directions-run',
  forearms: 'fitness-center',
  full_body: 'accessibility-new',
  cardio: 'directions-run',
};

// ─── Exercises ───────────────────────────────────────────────

export const EXERCISES: Exercise[] = [
  {
    id: 'ex_001',
    name: 'Barbell Bench Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    description: 'The king of chest exercises. Compound push movement targeting the pectorals.',
    instructions: [
      'Lie flat on the bench with feet on the floor',
      'Grip the bar slightly wider than shoulder width',
      'Unrack the bar and lower it to mid-chest',
      'Press the bar back up to starting position',
      'Keep your shoulder blades retracted throughout',
    ],
    equipment: ['barbell', 'bench'],
  },
  {
    id: 'ex_002',
    name: 'Incline Dumbbell Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    description: 'Targets the upper chest with a dumbbell press on an incline bench.',
    instructions: [
      'Set bench to 30-45 degree incline',
      'Hold dumbbells at shoulder height',
      'Press dumbbells up and slightly inward',
      'Lower with control to starting position',
    ],
    equipment: ['dumbbells', 'incline bench'],
  },
  {
    id: 'ex_003',
    name: 'Cable Flyes',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders'],
    description: 'Isolation movement for the chest using cables for constant tension.',
    instructions: [
      'Set cables to shoulder height',
      'Step forward with one foot for stability',
      'Bring hands together in front of chest with slight bend in elbows',
      'Slowly return to starting position',
    ],
    equipment: ['cable machine'],
  },
  {
    id: 'ex_004',
    name: 'Pull-ups',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    description: 'Bodyweight compound exercise for building a wide back.',
    instructions: [
      'Hang from bar with overhand grip wider than shoulders',
      'Pull yourself up until chin is over the bar',
      'Lower yourself with control',
      'Avoid swinging or kipping',
    ],
    equipment: ['pull-up bar'],
  },
  {
    id: 'ex_005',
    name: 'Barbell Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'forearms', 'core'],
    description: 'Heavy compound rowing movement for overall back thickness.',
    instructions: [
      'Hinge at hips with slight knee bend',
      'Grip bar slightly wider than shoulder width',
      'Pull bar to lower chest / upper abdomen',
      'Squeeze shoulder blades at the top',
      'Lower with control',
    ],
    equipment: ['barbell'],
  },
  {
    id: 'ex_006',
    name: 'Lat Pulldown',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    description: 'Cable machine exercise that mimics pull-ups with adjustable resistance.',
    instructions: [
      'Sit at the machine with thighs under pads',
      'Grip the bar wider than shoulder width',
      'Pull the bar down to upper chest',
      'Control the weight back up',
    ],
    equipment: ['lat pulldown machine'],
  },
  {
    id: 'ex_007',
    name: 'Overhead Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    description: 'Standing barbell press for shoulder strength and size.',
    instructions: [
      'Stand with feet shoulder width apart',
      'Hold bar at collarbone height with grip just outside shoulders',
      'Press bar overhead until arms are locked out',
      'Lower bar back to starting position with control',
    ],
    equipment: ['barbell'],
  },
  {
    id: 'ex_008',
    name: 'Lateral Raises',
    muscleGroup: 'shoulders',
    secondaryMuscles: [],
    description: 'Isolation exercise for the medial deltoid head.',
    instructions: [
      'Stand holding dumbbells at your sides',
      'Raise arms out to the sides until parallel with floor',
      'Keep a slight bend in your elbows',
      'Lower slowly - don\'t just drop them',
    ],
    equipment: ['dumbbells'],
  },
  {
    id: 'ex_009',
    name: 'Face Pulls',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['back'],
    description: 'Rear delt and rotator cuff exercise using a cable machine.',
    instructions: [
      'Set cable to face height with rope attachment',
      'Pull rope towards face, separating hands',
      'Squeeze shoulder blades together at peak contraction',
      'Return with control',
    ],
    equipment: ['cable machine', 'rope attachment'],
  },
  {
    id: 'ex_010',
    name: 'Barbell Curl',
    muscleGroup: 'biceps',
    secondaryMuscles: ['forearms'],
    description: 'Classic bicep exercise for building arm size.',
    instructions: [
      'Stand holding barbell with underhand grip',
      'Curl the bar up keeping elbows pinned to sides',
      'Squeeze at the top',
      'Lower with control - no swinging',
    ],
    equipment: ['barbell'],
  },
  {
    id: 'ex_011',
    name: 'Hammer Curls',
    muscleGroup: 'biceps',
    secondaryMuscles: ['forearms'],
    description: 'Dumbbell curl variation that also targets the brachialis.',
    instructions: [
      'Hold dumbbells with neutral grip (palms facing each other)',
      'Curl up keeping wrists straight',
      'Alternate arms or do both simultaneously',
    ],
    equipment: ['dumbbells'],
  },
  {
    id: 'ex_012',
    name: 'Tricep Pushdowns',
    muscleGroup: 'triceps',
    secondaryMuscles: [],
    description: 'Cable exercise for tricep isolation.',
    instructions: [
      'Stand at cable machine with rope or bar attachment',
      'Keep elbows at your sides',
      'Push the weight down until arms are extended',
      'Return to starting position with control',
    ],
    equipment: ['cable machine'],
  },
  {
    id: 'ex_013',
    name: 'Skull Crushers',
    muscleGroup: 'triceps',
    secondaryMuscles: [],
    description: 'Lying tricep extension with an EZ bar or dumbbells.',
    instructions: [
      'Lie on bench holding EZ bar above chest',
      'Lower bar to forehead by bending elbows',
      'Keep upper arms stationary',
      'Extend arms back to starting position',
    ],
    equipment: ['EZ bar', 'bench'],
  },
  {
    id: 'ex_014',
    name: 'Barbell Squat',
    muscleGroup: 'legs',
    secondaryMuscles: ['glutes', 'core'],
    description: 'The fundamental lower body compound movement.',
    instructions: [
      'Position bar on upper back (not neck)',
      'Stand with feet shoulder width apart, toes slightly out',
      'Squat down until thighs are parallel to floor',
      'Drive through heels to stand back up',
      'Keep chest up and core braced throughout',
    ],
    equipment: ['barbell', 'squat rack'],
  },
  {
    id: 'ex_015',
    name: 'Romanian Deadlift',
    muscleGroup: 'legs',
    secondaryMuscles: ['glutes', 'back'],
    description: 'Hip hinge movement targeting the hamstrings and glutes.',
    instructions: [
      'Hold barbell at hip height with overhand grip',
      'Push hips back while keeping legs mostly straight',
      'Lower bar along thighs until you feel hamstring stretch',
      'Drive hips forward to return to standing',
    ],
    equipment: ['barbell'],
  },
  {
    id: 'ex_016',
    name: 'Leg Press',
    muscleGroup: 'legs',
    secondaryMuscles: ['glutes'],
    description: 'Machine-based compound leg exercise with support for heavy loads.',
    instructions: [
      'Sit in leg press with back flat against pad',
      'Place feet shoulder width on platform',
      'Lower platform by bending knees to 90 degrees',
      'Press back up without locking knees',
    ],
    equipment: ['leg press machine'],
  },
  {
    id: 'ex_017',
    name: 'Walking Lunges',
    muscleGroup: 'legs',
    secondaryMuscles: ['glutes', 'core'],
    description: 'Dynamic unilateral leg exercise for strength and stability.',
    instructions: [
      'Hold dumbbells at your sides',
      'Step forward into a lunge position',
      'Both knees should be at roughly 90 degrees',
      'Push off front foot and step into next lunge',
    ],
    equipment: ['dumbbells'],
  },
  {
    id: 'ex_018',
    name: 'Plank',
    muscleGroup: 'core',
    secondaryMuscles: ['shoulders'],
    description: 'Isometric core exercise for building stability and endurance.',
    instructions: [
      'Get into push-up position on forearms',
      'Keep body in a straight line from head to heels',
      'Engage core - don\'t let hips sag or pike',
      'Hold for prescribed duration',
    ],
    equipment: [],
  },
  {
    id: 'ex_019',
    name: 'Cable Woodchops',
    muscleGroup: 'core',
    secondaryMuscles: ['shoulders'],
    description: 'Rotational core exercise using a cable machine.',
    instructions: [
      'Set cable to high position',
      'Stand sideways to machine, feet wider than shoulders',
      'Pull cable diagonally across body to opposite hip',
      'Control the return - don\'t let the weight snap back',
    ],
    equipment: ['cable machine'],
  },
  {
    id: 'ex_020',
    name: 'Hanging Leg Raises',
    muscleGroup: 'core',
    secondaryMuscles: ['forearms'],
    description: 'Advanced core exercise performed hanging from a bar.',
    instructions: [
      'Hang from pull-up bar with straight arms',
      'Raise legs until parallel with floor (or higher)',
      'Lower with control - avoid swinging',
      'For easier variation, bend knees',
    ],
    equipment: ['pull-up bar'],
  },
  {
    id: 'ex_021',
    name: 'Hip Thrust',
    muscleGroup: 'glutes',
    secondaryMuscles: ['legs'],
    description: 'The best exercise for glute activation and growth.',
    instructions: [
      'Sit on floor with upper back against bench',
      'Roll barbell over hips',
      'Drive hips up until body forms a straight line',
      'Squeeze glutes hard at the top',
      'Lower with control',
    ],
    equipment: ['barbell', 'bench'],
  },
  {
    id: 'ex_022',
    name: 'Standing Calf Raises',
    muscleGroup: 'calves',
    secondaryMuscles: [],
    description: 'Machine or free weight exercise targeting the gastrocnemius.',
    instructions: [
      'Stand on calf raise machine or step',
      'Rise up onto toes as high as possible',
      'Hold at top briefly',
      'Lower heels below platform for full stretch',
    ],
    equipment: ['calf raise machine'],
  },
  {
    id: 'ex_023',
    name: 'Wrist Curls',
    muscleGroup: 'forearms',
    secondaryMuscles: [],
    description: 'Isolation exercise for forearm flexors.',
    instructions: [
      'Sit with forearms resting on thighs, wrists hanging off knees',
      'Hold barbell with underhand grip',
      'Curl wrists up',
      'Lower slowly',
    ],
    equipment: ['barbell'],
  },
  {
    id: 'ex_024',
    name: 'Burpees',
    muscleGroup: 'full_body',
    secondaryMuscles: ['chest', 'legs', 'core'],
    description: 'Full body explosive movement for conditioning.',
    instructions: [
      'Start standing',
      'Drop to push-up position',
      'Perform a push-up',
      'Jump feet forward',
      'Jump up with arms overhead',
    ],
    equipment: [],
  },
  {
    id: 'ex_025',
    name: 'Treadmill Running',
    muscleGroup: 'cardio',
    secondaryMuscles: ['legs', 'core'],
    description: 'Steady state or interval running on a treadmill.',
    instructions: [
      'Start with a 2-3 minute walking warm-up',
      'Increase speed to target pace',
      'Maintain proper running form',
      'Cool down with 2-3 minutes walking',
    ],
    equipment: ['treadmill'],
  },
  {
    id: 'ex_026',
    name: 'Dumbbell Bench Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    description: 'Bench press variation allowing for greater range of motion.',
    instructions: [
      'Lie on bench with a dumbbell in each hand',
      'Press dumbbells up directly over chest',
      'Lower until upper arms are parallel to floor',
      'Press back up to starting position',
    ],
    equipment: ['dumbbells', 'bench'],
  },
  {
    id: 'ex_027',
    name: 'Seated Cable Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    description: 'Cable rowing movement for mid-back thickness.',
    instructions: [
      'Sit at cable row station with feet on platform',
      'Grab V-bar handle with both hands',
      'Pull handle to abdomen, squeezing shoulder blades',
      'Extend arms back slowly',
    ],
    equipment: ['cable machine'],
  },
  {
    id: 'ex_028',
    name: 'Dips',
    muscleGroup: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    description: 'Compound bodyweight exercise for triceps and chest.',
    instructions: [
      'Grip parallel bars and lift yourself up',
      'Lower body by bending elbows to about 90 degrees',
      'Keep torso upright for tricep focus (lean forward for chest)',
      'Press back up to starting position',
    ],
    equipment: ['dip bars'],
  },
  {
    id: 'ex_029',
    name: 'Bulgarian Split Squat',
    muscleGroup: 'legs',
    secondaryMuscles: ['glutes', 'core'],
    description: 'Unilateral leg exercise for strength and balance.',
    instructions: [
      'Stand in front of bench, place rear foot on bench behind you',
      'Hold dumbbells at sides',
      'Lower until front thigh is parallel to floor',
      'Drive through front heel to stand back up',
    ],
    equipment: ['dumbbells', 'bench'],
  },
  {
    id: 'ex_030',
    name: 'Mountain Climbers',
    muscleGroup: 'cardio',
    secondaryMuscles: ['core', 'shoulders', 'legs'],
    description: 'Dynamic bodyweight cardio exercise.',
    instructions: [
      'Start in push-up position',
      'Drive one knee toward chest',
      'Quickly switch legs',
      'Continue alternating at a fast pace',
    ],
    equipment: [],
  },
];

// ─── Workout Plans ───────────────────────────────────────────

const makeSet = (reps: number, weight: number): { id: string; reps: number; weight: number; completed: boolean } => ({
  id: `set_${Math.random().toString(36).slice(2, 8)}`,
  reps,
  weight,
  completed: false,
});

const buildExercise = (
  exerciseId: string,
  setsConfig: Array<[number, number]>, // [reps, weight]
  restSeconds = 90,
): {
  exerciseId: string;
  exercise: Exercise;
  sets: Array<{ id: string; reps: number; weight: number; completed: boolean }>;
  restSeconds: number;
} => {
  const exercise = EXERCISES.find(e => e.id === exerciseId)!;
  return {
    exerciseId,
    exercise,
    sets: setsConfig.map(([reps, weight]) => makeSet(reps, weight)),
    restSeconds,
  };
};

export const WORKOUT_PLANS: Workout[] = [
  {
    id: 'w_001',
    name: 'Push Day',
    description: 'Chest, shoulders, and triceps focused workout.',
    difficulty: 'intermediate',
    estimatedMinutes: 55,
    targetMuscles: ['chest', 'shoulders', 'triceps'],
    category: 'strength',
    createdAt: '2024-09-15T10:00:00Z',
    exercises: [
      buildExercise('ex_001', [[8, 80], [8, 80], [6, 85], [6, 85]]),
      buildExercise('ex_002', [[10, 28], [10, 28], [8, 32]]),
      buildExercise('ex_007', [[8, 50], [8, 50], [6, 55]]),
      buildExercise('ex_008', [[12, 12], [12, 12], [10, 14]], 60),
      buildExercise('ex_012', [[12, 25], [12, 25], [10, 30]], 60),
    ],
  },
  {
    id: 'w_002',
    name: 'Pull Day',
    description: 'Back and biceps workout with heavy compounds.',
    difficulty: 'intermediate',
    estimatedMinutes: 50,
    targetMuscles: ['back', 'biceps'],
    category: 'strength',
    createdAt: '2024-09-15T10:00:00Z',
    exercises: [
      buildExercise('ex_004', [[8, 0], [8, 0], [6, 0], [6, 0]], 120),
      buildExercise('ex_005', [[8, 70], [8, 70], [6, 75]]),
      buildExercise('ex_027', [[10, 55], [10, 55], [8, 60]]),
      buildExercise('ex_009', [[15, 15], [15, 15], [12, 17.5]], 60),
      buildExercise('ex_010', [[10, 30], [10, 30], [8, 32.5]], 60),
    ],
  },
  {
    id: 'w_003',
    name: 'Leg Day',
    description: 'Complete lower body session. Quads, hamstrings, and glutes.',
    difficulty: 'advanced',
    estimatedMinutes: 65,
    targetMuscles: ['legs', 'glutes', 'calves'],
    category: 'strength',
    createdAt: '2024-09-16T10:00:00Z',
    exercises: [
      buildExercise('ex_014', [[8, 100], [8, 100], [6, 110], [5, 115]], 150),
      buildExercise('ex_015', [[10, 70], [10, 70], [8, 80]]),
      buildExercise('ex_016', [[12, 150], [12, 150], [10, 170]]),
      buildExercise('ex_021', [[12, 80], [12, 80], [10, 90]]),
      buildExercise('ex_022', [[15, 40], [15, 40], [12, 45]], 60),
    ],
  },
  {
    id: 'w_004',
    name: 'Upper Body Strength',
    description: 'Heavy compound movements for overall upper body development.',
    difficulty: 'advanced',
    estimatedMinutes: 60,
    targetMuscles: ['chest', 'back', 'shoulders'],
    category: 'strength',
    createdAt: '2024-09-20T10:00:00Z',
    exercises: [
      buildExercise('ex_001', [[5, 90], [5, 90], [3, 95], [3, 100]], 180),
      buildExercise('ex_005', [[5, 80], [5, 80], [5, 85]], 150),
      buildExercise('ex_007', [[5, 55], [5, 55], [5, 60]], 150),
      buildExercise('ex_028', [[8, 0], [8, 0], [8, 0]], 120),
    ],
  },
  {
    id: 'w_005',
    name: 'Full Body Beginner',
    description: 'Great introductory workout hitting all major muscle groups.',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    targetMuscles: ['chest', 'back', 'legs', 'core'],
    category: 'strength',
    createdAt: '2024-09-22T10:00:00Z',
    exercises: [
      buildExercise('ex_026', [[10, 16], [10, 16], [10, 16]]),
      buildExercise('ex_006', [[10, 35], [10, 35], [10, 35]]),
      buildExercise('ex_016', [[12, 80], [12, 80], [12, 80]]),
      buildExercise('ex_018', [[30, 0], [30, 0]], 60), // 30 seconds hold
    ],
  },
  {
    id: 'w_006',
    name: 'HIIT Blast',
    description: '20-minute high intensity interval training session.',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    targetMuscles: ['full_body', 'cardio'],
    category: 'hiit',
    createdAt: '2024-10-01T10:00:00Z',
    exercises: [
      buildExercise('ex_024', [[15, 0], [15, 0], [12, 0]], 30),
      buildExercise('ex_030', [[20, 0], [20, 0], [20, 0]], 30),
      buildExercise('ex_017', [[12, 0], [12, 0], [10, 0]], 30),
      buildExercise('ex_018', [[45, 0], [45, 0]], 30), // 45 sec hold
    ],
  },
  {
    id: 'w_007',
    name: 'Arm Day',
    description: 'Dedicated arm session for biceps and triceps.',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    targetMuscles: ['biceps', 'triceps', 'forearms'],
    category: 'strength',
    createdAt: '2024-10-05T10:00:00Z',
    exercises: [
      buildExercise('ex_010', [[10, 25], [10, 25], [8, 27.5]], 75),
      buildExercise('ex_013', [[10, 25], [10, 25], [8, 27.5]], 75),
      buildExercise('ex_011', [[12, 14], [12, 14], [10, 16]], 60),
      buildExercise('ex_012', [[12, 22.5], [12, 22.5], [10, 25]], 60),
      buildExercise('ex_023', [[15, 20], [15, 20]], 45),
    ],
  },
  {
    id: 'w_008',
    name: 'Core Crusher',
    description: 'Intense core and ab focused workout.',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    targetMuscles: ['core'],
    category: 'strength',
    createdAt: '2024-10-10T10:00:00Z',
    exercises: [
      buildExercise('ex_018', [[60, 0], [60, 0], [45, 0]], 60),
      buildExercise('ex_020', [[12, 0], [12, 0], [10, 0]], 60),
      buildExercise('ex_019', [[12, 20], [12, 20], [12, 20]], 60),
    ],
  },
  {
    id: 'w_009',
    name: 'Cardio & Conditioning',
    description: 'Mixed cardio session for endurance and fat loss.',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    targetMuscles: ['cardio', 'full_body'],
    category: 'cardio',
    createdAt: '2024-10-12T10:00:00Z',
    exercises: [
      buildExercise('ex_025', [[1, 0]], 60), // 1 = number of intervals, weight unused
      buildExercise('ex_024', [[10, 0], [10, 0], [10, 0]], 45),
      buildExercise('ex_030', [[30, 0], [30, 0], [30, 0]], 30),
    ],
  },
  {
    id: 'w_010',
    name: 'PPL - Push (Hypertrophy)',
    description: 'High volume push day optimized for muscle growth.',
    difficulty: 'advanced',
    estimatedMinutes: 70,
    targetMuscles: ['chest', 'shoulders', 'triceps'],
    category: 'strength',
    createdAt: '2024-10-20T10:00:00Z',
    exercises: [
      buildExercise('ex_001', [[10, 70], [10, 70], [8, 75], [8, 75]]),
      buildExercise('ex_002', [[12, 24], [12, 24], [10, 28], [10, 28]]),
      buildExercise('ex_003', [[15, 15], [15, 15], [12, 17.5]]),
      buildExercise('ex_007', [[10, 42.5], [10, 42.5], [8, 45]]),
      buildExercise('ex_008', [[15, 10], [15, 10], [12, 12], [12, 12]], 60),
      buildExercise('ex_013', [[12, 22.5], [12, 22.5], [10, 25]]),
    ],
  },
];

// ─── Achievements ────────────────────────────────────────────

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_first_workout',
    title: 'First Step',
    description: 'Complete your first workout',
    icon: 'star',
    requirement: 1,
    progress: 0,
  },
  {
    id: 'ach_10_workouts',
    title: 'Getting Serious',
    description: 'Complete 10 workouts',
    icon: 'trending-up',
    requirement: 10,
    progress: 0,
  },
  {
    id: 'ach_50_workouts',
    title: 'Dedicated',
    description: 'Complete 50 workouts',
    icon: 'fitness-center',
    requirement: 50,
    progress: 0,
  },
  {
    id: 'ach_100_workouts',
    title: 'Centurion',
    description: 'Complete 100 workouts',
    icon: 'emoji-events',
    requirement: 100,
    progress: 0,
  },
  {
    id: 'ach_7_day_streak',
    title: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: 'local-fire-department',
    requirement: 7,
    progress: 0,
  },
  {
    id: 'ach_30_day_streak',
    title: 'Unstoppable',
    description: 'Maintain a 30-day streak',
    icon: 'whatshot',
    requirement: 30,
    progress: 0,
  },
  {
    id: 'ach_1000kg_volume',
    title: 'Ton Lifter',
    description: 'Lift 1,000 kg total volume in one session',
    icon: 'fitness-center',
    requirement: 1000,
    progress: 0,
  },
  {
    id: 'ach_5_week',
    title: 'Consistency King',
    description: 'Complete 5 workouts in a single week',
    icon: 'calendar-today',
    requirement: 5,
    progress: 0,
  },
];

export const DEFAULT_REST_SECONDS = 90;
export const MAX_WORKOUT_DURATION_HOURS = 3;

// TODO: move these to user settings when we add preferences
export const DEFAULT_WEIGHT_UNIT = 'kg';
export const DEFAULT_HEIGHT_UNIT = 'cm';
